version: "3"
services: 
  db-as:
    image: mariadb
    environment:.
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - twojVOLUMEN:/var/lib/mysql  

  adminer-as:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db-as
    ports:
      - TWOJPORT-81X8:8080
### DODAJ kontener webapp bazujący na obrazie z7-TWOJLOGIN 

volumes:
  uzupełnij
